cnc_websocket: wss://placetud-headless.yanick.gay/api/ws
map_url: https://placetud-headless.yanick.gay/maps/

accounts: 
  - 
    username: username
    password: password
  - 
    username: another_username
    password: another_password